/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_samsungimaging_asphodel_multimedia_FFmpegJNI */

#ifndef _Included_za_co_snyders_multimedia_FFmpegJNI
#define _Included_za_co_snyders_multimedia_FFmpegJNI
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_za_co_snyders_multimedia_FFmpegJNI_ffplayMain
  (JNIEnv *, jobject, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
